export const questions: string[] = [
  "What is your happiest memory?",
  "What is your biggest fear?",
  "What is your dream vacation destination?",
  "What is your guilty pleasure?",
  "What is the most adventurous thing you've ever done?",
  "What is your favorite thing about yourself?",
  "What is one thing you'd change about the world?",
  "What makes you laugh the hardest?",
  "What is your biggest pet peeve?",
  "What song always puts you in a good mood?",
  "What's a skill you wish you had?",
  "What's the best advice you've ever received?",
  "What is your earliest childhood memory?",
  "What's a secret talent you have?",
  "Who has been the most influential person in your life?",
  "What does your perfect day look like?",
  "What's the most embarrassing thing that's happened to you?",
  "What are you most grateful for?",
  "What's a deal-breaker in a relationship for you?",
  "What is your love language?",
  "What's the craziest thing on your bucket list?",
  "What's one thing people always misunderstand about you?",
  "What's your favorite way to spend a weekend?",
  "If you could have dinner with anyone, dead or alive, who would it be?",
  "What's your comfort food?",
  "What's the most meaningful gift you've ever received?",
  "What's one thing you could talk about for hours?",
  "What quality do you admire most in others?",
  "What was the last thing that made you cry?",
  "What's a belief you held strongly but changed your mind about?",
  "What is the bravest thing you've ever done?",
  "What is the most romantic thing you can imagine?",
  "What does 'home' mean to you?",
  "What's a childhood dream you still hold onto?",
  "What are you most proud of?",
  "What is your biggest regret?",
  "What do you think is the meaning of life?",
  "What do you value most in a friendship?",
  "What's the kindest thing someone has done for you?",
  "If you could relive one moment, what would it be?",
  "What's your idea of a perfect date?",
  "What three words would your friends use to describe you?",
  "What do you wish you spent more time doing?",
  "What's a habit you're trying to break?",
  "What makes you feel most alive?",
  "What do you want to be remembered for?",
  "What's your favorite family tradition?",
  "What's a movie that changed your perspective?",
  "What's the most important lesson life has taught you?",
  "What are you looking forward to most right now?",
  "What does success mean to you?",
  "What was the hardest decision you ever had to make?",
  "What makes you feel loved?",
  "What's a compliment you'll never forget?",
  "What's a topic you feel strongly about?",
  "What's your favorite thing to do when you're alone?",
  "If money were no object, what would you do with your life?",
  "What's something you've never told anyone?",
  "What does trust mean to you?",
  "What's a tradition you want to start?",
  "What fictional character do you relate to most?",
  "What's a risk you're glad you took?",
  "What scares you about the future?",
  "What excites you about the future?",
  "What's something you need to forgive yourself for?",
  "How do you handle conflict?",
  "What's the best compliment you could receive?",
  "What's your biggest insecurity?",
  "What makes you feel safe?",
  "What's a question you wish people would ask you more often?",
  "What is your definition of happiness?",
  "What does loyalty mean to you?",
  "What role does faith or spirituality play in your life?",
  "What's a boundary you've had to set?",
  "What's your go-to way to de-stress?",
  "What's something that always brings you peace?",
  "If you could master one instrument, what would it be?",
  "What's the most spontaneous thing you've ever done?",
  "What's a cause you're passionate about?",
  "What do you think about before falling asleep?",
  "What's the hardest thing about being you?",
  "What's the best part of your daily routine?",
  "What's a lesson you had to learn the hard way?",
  "What's something you wish you could say to your younger self?",
  "What do you need more of in your life?",
  "What do you need less of in your life?",
  "What's a small thing that makes a big difference to you?",
  "What does forgiveness look like to you?",
  "What would you do if you knew you couldn't fail?",
  "What's something you wish more people knew about you?",
  "What does it mean to truly know someone?",
  "What's the most beautiful thing you've ever seen?",
  "When do you feel most like yourself?",
  "What question would you most like the answer to?",
  "What's something you'd like to learn about me?",
  "What's the most important thing in your life right now?",
  "How do you show someone you care?",
  "What would make today perfect?",
  "What do you think we have in common that isn't obvious?",
  "What's a moment you felt completely understood?",
  "What do you think makes a relationship last?",
];
